name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: スクレイピング
        run: |
          git clone https://github.com/yuzuru-program/scraping-go-yahoo.git ci
          cd ci
          go get github.com/PuerkitoBio/goquery
          go run index.go
